name: Build Blender Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Ninja Build Tool
      uses: llvm/actions/install-ninja@main

    # 1. Pobranie submodułu LFS
    - name: Pull External LFS Libraries
      shell: cmd
      run: |
        cd blender-main\blender
        git submodule update --init --recursive lib/windows_x64
        cd lib\windows_x64
        git lfs pull

    # 2. DIAGNOSTYKA: Wypisanie zawartości katalogu bibliotek do logów GH Actions
    - name: Debug - Inspect Directory Structure
      shell: cmd
      run: |
        echo === SPRAWDZANIE KATALOGU BASE ===
        cd blender-main\blender
        cd
        echo === SPRAWDZANIE KATALOGU LIB ===
        if exist lib\windows_x64 (
          dir lib\windows_x64
        ) else (
          echo FOLDER lib\windows_x64 NIE ISTNIEJE!
        )

    # 3. Modyfikacja kodów źródłowych
    - name: Run Patch and Prepare Files
      shell: cmd
      run: |
        python PrepareFiles\patch_and_compile.py

    # 4. Kompilacja
    - name: Build Blender
      shell: cmd
      working-directory: blender-main/blender
      run: |
        make.bat ninja release
